api/urls.py
from django.conf.urls.defaults import patterns, include, url
from tastypie.api import Api
from api import GameResource, PlayerResource

v1_api = Api(api_name='v1')
v1_api.register(PlayerResource())
v1_api.register(GameResource())

urlpatterns = patterns('',
  (r'', include(v1_api.urls)),
)

game/urls.py
from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('',
    url(r'^create/', 'game.views.create', name='create_game'),
    url(r'^(?P<game_id>\d+)/$', 'game.views.game', name='game'),
    url(r'^$', 'game.views.games', name='games'),
    url(r'^(?P<game_id>\d+)/turn/(?P<turn_id>\d+)/$', 'game.views.turn', name='turn'),
    url(r'^(?P<game_id>\d+)/submission/$', 'game.views.submission', name='submission'),
    url(r'^(?P<game_id>\d+)/turn/(?P<turn_id>\d+)/submission/(?P<page>\d+)/$', 'game.views.submission', name='submission'),
)

home/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('',
    url(r'^$', 'home.views.home', name='home'),
)

socialbum/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', include('home.urls')),
    url(r'^facebook/', include('facebook.urls')),
    url(r'^album/', include('album.urls')),
    url(r'^game/', include('game.urls')),
    url(r'^api/', include('api.urls')),

    # url(r'^accounts/', include('registration.backends.simple.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

facebook/models.py
from django.db import models

# Create your models here.
import simplejson
import urllib
from django.contrib.auth.models import User

class FacebookSessionError(Exception):
    def __init__(self, error_type, message):
        self.message = message
        self.type = error_type
    def get_message(self):
        return self.message
    def get_type(self):
        return self.type
    def __unicode__(self):
        return u'%s: "%s"' % (self.type, self.message)

class FacebookSession(models.Model):

    access_token = models.CharField(max_length=255, unique=True)
    expires = models.IntegerField(null=True)

    user = models.ForeignKey(User, null=True)
    uid = models.BigIntegerField(unique=True, null=True)

    def picture_url(self):
        return "http://graph.facebook.com/" + str(self.uid) + "/picture"

    class Meta:
        unique_together = (('user', 'uid'), ('access_token', 'expires'))

    def query(self, object_id, connection_type=None, metadata=False):

        url = 'https://graph.facebook.com/%s' % (object_id)
        if connection_type:
            url += '/%s' % (connection_type)

        params = {'access_token': self.access_token}
        if metadata:
            params['metadata'] = 1

        url += '?' + urllib.urlencode(params)
        response = simplejson.load(urllib.urlopen(url))
        if 'error' in response:
            error = response['error']
            raise FacebookSessionError(error['type'], error['message'])
        return response

    def get_facebook_profile(self):
        fb_profile = urllib.urlopen('https://graph.facebook.com/me?access_token=%s' % self.access_token)
        return simplejson.load(fb_profile)

    def get_friends(self):
        fb_friends = urllib.urlopen('https://graph.facebook.com/me/friends?access_token=%s' % self.access_token)
        return simplejson.load(fb_friends)

game/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Game(models.Model):
    name = models.CharField(max_length=64)
    users = models.ManyToManyField(User, through="Player")
    current_turn = models.OneToOneField('Turn', related_name="+", null=True)
    completed = models.BooleanField(default=False)
    deleted = models.BooleanField(default=False)
    winner = models.OneToOneField('Player', null=True, related_name='+')

class Turn(models.Model):
    STATUSES = (
        (0, 'Choose Topic'),
        (1, 'Waiting Submissions / Select Winner'),
        (2, 'Turn End'),
    )

    game = models.ForeignKey(Game)
    num = models.PositiveSmallIntegerField()
    judge = models.ForeignKey(User)
    game_topic = models.OneToOneField('GameTopic', null=True)
    winner = models.OneToOneField('Submission', null=True, related_name='+')
    status = models.PositiveSmallIntegerField(default=0, choices=STATUSES)

class Topic(models.Model):
    text = models.TextField()
    deleted = models.BooleanField(default=False)

class GameTopic(models.Model):
    topic = models.ForeignKey(Topic)
    game = models.ForeignKey('Game')
    used = models.BooleanField(default=False)

class Submission(models.Model):
    clickX = models.TextField()
    clickY = models.TextField()
    clickDrag = models.TextField()
    clickColor = models.TextField()
    clickSize = models.TextField()
    player = models.ForeignKey('Player')
    turn = models.ForeignKey(Turn)

class Player(models.Model):
    user = models.ForeignKey(User)
    game = models.ForeignKey(Game)
    points = models.PositiveSmallIntegerField()

game/forms.py
from django import forms
from django.contrib.auth.models import User
from game.models import Game, GameTopic, Submission

class GameForm(forms.Form):
    users = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple(),required=True,queryset=User.objects.all())

class GameTopicChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.topic.text

class GameTopicForm(forms.Form):
    game_topic = forms.IntegerField(widget=forms.HiddenInput,required=True)

class SubmissionChoiceForm(forms.Form):
    submission = forms.ModelChoiceField(widget=forms.RadioSelect(), required=True,empty_label=None,queryset=Submission.objects.all())

game/views.py
from django.shortcuts import render_to_response
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import RequestContext
from django.contrib.auth.decorators import login_required

from game.models import Game, GameTopic, Player, Topic, Turn, Submission
from game.forms import GameTopicForm, GameForm, SubmissionChoiceForm
from facebook.views import get_friends_list
from facebook.models import FacebookSession

import json

NUM_TOPIC_CHOICES = 3

@login_required
def games(request):
    print request.user
    active_games = Game.objects.filter(users__id=request.user.id).filter(completed=False)
    completed_games = Game.objects.filter(users__id=request.user.id).filter(completed=True)
    template_context = {'games':active_games,
                        'completed_games':completed_games}
    return render_to_response('games.html', template_context, context_instance=RequestContext(request))

@login_required
def create(request):
    if request.method == 'POST':
        gf = GameForm(request.POST)
        if gf.is_valid():
            users = gf.cleaned_data['users']
            
            g = Game()
            g.save()

            for user in users:
                p = Player.objects.create(user=user, 
                                           game=g,
                                           points=0)
            p = Player.objects.create(user=request.user,
                                       game=g,
                                       points=0)
            

            topics = Topic.objects.filter(deleted=False).order_by('?')
            for topic in topics:
                game_topic = GameTopic.objects.create(topic=topic,
                                                        game=g)
            #create turn
            turn = Turn.objects.create(game=g,
                                       num=1,
                                       judge=request.user)
            g.current_turn = turn
            g.save()
            
            return HttpResponseRedirect(reverse('game', kwargs={'game_id':g.id}))
    else:
        gf = GameForm()

    try:
        fb_profile = FacebookSession.objects.get(user=request.user)
    except FacebookSession.DoesNotExist:
        raise Http404

    user_friends_list, user_friends_queryset, only_fb_friends_list = get_friends_list(fb_profile)

    gf.fields["users"].queryset = user_friends_queryset
    template_context = {'gf': gf,
                        'user_friends_list':user_friends_list,
                        'fb_friends_list':only_fb_friends_list}
    return render_to_response('create_game.html', template_context, context_instance=RequestContext(request))

@login_required
def game(request, game_id):
    try:
        g = Game.objects.get(id=game_id)
    except Game.DoesNotExist:
        raise Http404

    if g.completed:
        return show_point_table(request, g)

    turn = g.current_turn

    if turn.status == 0:
        if turn.judge == request.user:
            return choose_topic(request, g)
        else:
            return show_point_table(request, g)
    elif turn.status == 1:
        if turn.judge == request.user:
            return HttpResponseRedirect(reverse('submission', kwargs={
                'game_id':game_id,
                'turn_id':g.current_turn.id,
                'page':0,
            }))
        else:
            return draw(request, g)
    else:
        start_new_turn(request=request, game=g)
        return game(request, game_id)

@login_required
def choose_topic(request, game):
    #check that person making request is the current turn's judge

    if request.method == 'POST':
        game_topic_form = GameTopicForm(request.POST)
        if game_topic_form.is_valid():
            #need to check that game topic has not been used already
            """
            game_topic_choices = game.gametopic_set.filter(used=False)[0:3]
            for game_topic_choice in game_topic_choices:
                game_topic_choice.used = True
                game_topic_choice.save()
            """

            game_topic_id = game_topic_form.cleaned_data['game_topic']
            try:
                game_topic = GameTopic.objects.get(id=game_topic_id)
            except GameTopic.DoesNotExist:
                game_topic = None

            if game_topic:
                game_topic.used = True
                game_topic.save()
                game.current_turn.status = 1
                game.current_turn.game_topic = game_topic
                game.current_turn.save()
                return HttpResponseRedirect(reverse('game', kwargs={'game_id':game.id}))
    else:
        game_topic_form = GameTopicForm()

    game_topics = game.gametopic_set.filter(used=False)
    selected_game_topics = select_three_random(game.current_turn.num, list(game_topics))
    template_context = {'game_topic_form':game_topic_form,
                        'game':game,
                        'game_topics':selected_game_topics}

    return render_to_response('choose_topic.html',
                              template_context,
                              context_instance=RequestContext(request)) 

#This function takes a turn number and a list of game topics and return three "random" topics
#Random meaning the results will be different for each turn number, but the same for a given number
def select_three_random(turn_num, game_topics):
    num_game_topics = len(game_topics)

    if num_game_topics < NUM_TOPIC_CHOICES :
        return game_topics

    selected_game_topics = []
    for i in xrange(0,NUM_TOPIC_CHOICES):
        idx = some_hash(turn_num + i, num_game_topics-i)
        selected_game_topics.append(game_topics[idx])
        game_topics[idx] = game_topics[num_game_topics - i - 1]
    return selected_game_topics

def some_hash(num, buckets):
    return num*2654435761 % buckets;

def show_point_table(request, game):
    players = game.player_set.all()
    turns = game.turn_set.filter(status=2)

    if turns:
        prev_turn = turns.order_by('id').reverse()[0]
    else:
        prev_turn = None

    template_context = {'players':players,
                        'turns':turns,
                        'prev_turn':prev_turn,
                        'game':game}
    return render_to_response('points_table.html',
                              template_context,
                              context_instance=RequestContext(request)) 

def pick_winner(request, game):
    is_judge = game.current_turn.judge == request.user
    sub_choice_form = None
    submissions = Submission.objects.filter(turn=game.current_turn)

    if is_judge:
        if request.method == 'POST':
            sub_choice_form = SubmissionChoiceForm(request.POST)
            if sub_choice_form.is_valid():
                submission = sub_choice_form.cleaned_data['submission']
                game.current_turn.winner = submission
                game.current_turn.status = 2
                game.current_turn.save()
                player = submission.player
                player.points += 1
                player.save()
                if player.points >= 3:
                    game.completed = True
                    game.winner = player
                    game.save()
                else:
                    start_new_turn(request, game)

                return HttpResponseRedirect(reverse('game', kwargs={'game_id':game.id}))
        else:
            sub_choice_form = SubmissionChoiceForm()

        sub_choice_form.fields["submission"].queryset = submissions

    return show_submissions(request, game, is_judge, sub_choice_form)


def start_new_turn(request, game):
    turn = Turn(game=game,
                num=game.current_turn.num+1,
                status=0)
    users_list = list(game.users.values_list('id', flat=True))
    next_judge_id = users_list[(users_list.index(game.current_turn.judge.id)+1)%len(users_list)]
    turn.judge = game.users.get(id=next_judge_id)
    turn.save()
    game.current_turn = turn
    game.save()

@login_required
def show_submissions(request, game, is_judge=False, sub_choice_form=None):
    # should check to see if user is judge
    submissions = Submission.objects.filter(turn=game.current_turn)

    if not submissions.exists():
        return show_point_table(request, game)

    from django.core import serializers
    submissions_json = serializers.serialize('json',
                                            submissions,
                                            fields=('id', 'clickX', 'clickY', 'clickDrag', 'clickSize', 'clickColor'))

    template_context = {'judge':is_judge,
                        'game':game,
                        'turn':game.current_turn,
                        'submissions':submissions,
                        'submissions_json':submissions_json,
                        'sub_choice_form':sub_choice_form}

    return render_to_response('submissions.html',
                              template_context,
                              context_instance=RequestContext(request))

def turn(request, game_id, turn_id):

    try:
        game = Game.objects.get(id=game_id)
    except:
        raise Http404

    try:
        turn = Turn.objects.get(id=turn_id)
    except:
        raise Http404

    if turn == game.current_turn and not game.completed:
        return HttpResponseRedirect(reverse('game', kwargs={'game_id':game_id}))

    return submission(request, game_id, turn_id, 0)

@login_required
def submission(request, game_id, turn_id=None, page=0):

    page = int(page)

    try:
        game = Game.objects.get(id=game_id)
    except:
        raise Http404

    if not turn_id:
        turn = game.current_turn
    else:
        try:
            turn = Turn.objects.get(id=turn_id)
        except:
            raise Http404

    submissions = turn.submission_set.all()

    if not submissions:
        return show_point_table(request, game)

    try:

home/views.py
# Create your views here.
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from facebook.models import FacebookSession
from album.forms import AlbumForm
from django.contrib.auth.decorators import login_required

def home(request):

    try:
        #facebook_profile = request.user.facebook_session.get_facebook_profile()
        facebook_profile = FacebookSession.objects.get(user=request.user)
    except:
        facebook_profile = None

    if facebook_profile !=None:
        album_form = AlbumForm();
        albums = request.user.album_set.all()
    else:
        album_form = None
        albums = None

    return render_to_response('home.html',
                              { 'facebook_profile': facebook_profile,
                                'album_form': album_form,
                                'albums': albums },
                              context_instance=RequestContext(request))

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}PaintsParty{%  endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="{{ STATIC_URL }}css/bootstrap.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/global.css" rel="stylesheet" type="text/css">
    {% block header_css %}
    {% endblock %}
    <style type="text/css">
      body {
        padding-top:60px;
      }

      @media (max-width: 980px) {
        /* Enable use of floated navbar text */
        .navbar-text.pull-right {
          float: none;
          padding-left: 5px;
          padding-right: 5px;
        }
      }
    </style>
    <link href="{{ STATIC_URL }}css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <!--
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="../assets/ico/favicon.png">
    -->

    <!-- javascript -->
    <!-- <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script> -->
    <script src="{{  STATIC_URL }}js/jquery-1.10.1.min.js"></script>
    <script src="{{  STATIC_URL }}js/holder.js"></script>
    {% block header_js %}
    {% endblock %}

  </head>

  <body>
    {% block header %}
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <!--
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          -->
          <a class="brand" href="{% url 'games' %}">PaintsParty</a>
          <div>
            {% if user.is_authenticated %}
                <ul class="nav pull-right">
                  <li class="dropdown">
                    <a class="dropdown-toggle" id="user-nav" role="button" data-toggle="dropdown" data-target="#" href="#">
                      <img src="http://graph.facebook.com/{{ user.facebooksession_set.all.0.uid }}/picture?width=30&height=30" /> {{ user.first_name }}
                      <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="user-nav">
                      <li role="presentation"><a role="menuitem" href="{% url 'logout' %}">Logout</a></li>
                    </ul>
                  </li>
                </ul>
            {% endif %}
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    {% endblock %}

    <div class="container-fluid middle-container">
      <div class="row-fluid">
        <div class="span12">
          {%  block content %}{% endblock %}
        </div><!--/span-->
      </div><!--/row-->
      <footer>
        {% block footer %}
        {% endblock %}
      </footer>
    </div><!--/.fluid-container-->

    <div class="navbar navbar-fixed-bottom">
      {% block navbar_bottom %}
      {% endblock %}
    </div>

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{{ STATIC_URL }}js/bootstrap.js"></script>
    {% block footer_js %}{% endblock %}
  </body>
</html>

templates/choose_topic.html
{% extends "base.html" %}

{% block header_css %}
  <link href="{{ STATIC_URL }}css/contacts.css" rel="stylesheet" type="text/css">
{% endblock %}

{% block title %}
Choose a topic
{% endblock %}

{% block content %}
  <p>Round {{ game.current_turn.num }}: Choose a topic</p>
{% if game_topic_form.game_topic.errors %}
Error selecting topic
{% endif %}
<form id="topic-form" action="{% url 'game' game.id %}" method="post">
  {% csrf_token %}
  <table id="topic-table" class="table table-bordered table-hover">
    {% for game_topic in game_topics %}
    <tr class="topic-row">
      <td class="topic-cell" name="{{ game_topic.id }}">
        {{ game_topic.topic.text }}
      </td>
    </tr>
    {% endfor %}
  </table>
  <div class="">
    {{ game_topic_form.game_topic }}
  </div>
  <div class="text-center">
    <button id="topic-btn" type="submit" class="btn btn-primary select-topic-btn" disabled="disabled">Select Topic</button>
  </div>
</form>
{% endblock %}

{% block footer_js %}
  <script src="{{ STATIC_URL }}js/contacts.js"></script>
{% endblock %}

templates/contacts.html
{%  extends 'base.html' %}

{% block header_css %}
  <link href="{{ STATIC_URL }}css/contacts.css" rel="stylesheet" type="text/css">
{% endblock %}

{%  block content %}

  <div class="create-game-container most-padding-top">
    <button type="submit" class="btn btn-primary create-game-btn">Start Game</button>
  </div>

  <div class="add-user-container most-padding-top">
    <h4>Start a game with</h4>
    <table class="table">
    {% for friend in app_friends_list %}
      <tr class="add-user-row">
        <td>
          <img src="{{ friend.picture_url }}"/>
        </td>
        <td>
          {{ friend.name }}
        </td>
        <td>
          <button type="submit" class="btn btn-primary add-user-btn add-user-btn">Add</button>
        </td>
      </tr>
    {% endfor %}
    </table>
  </div>
  <div class="invite-friends-container most-padding-top">
    <h4>Invite Friends</h4>

    <table class="table">
    {% for friend in fb_friends_list %}
      <tr>
        <td>
          <img src="{{ friend.picture_url }}"/>
        </td>
        <td>
        {{ friend.name }}
        </td>
        <td>
          <button type="submit" class="btn btn-primary">Invite</button>
        </td>
      </tr>
    {% endfor %}
    </table>
  </div>
{%  endblock %}


{% block footer_js %}
  <script src="{{ STATIC_URL }}js/contacts.js"></script>
{% endblock %}

templates/create_game.html
{%  extends 'base.html' %}

{% block header_css %}
  <link href="{{ STATIC_URL }}css/contacts.css" rel="stylesheet" type="text/css">
{% endblock %}

{%  block content %}
  <div class="add-user-container most-padding-top">
    <h4>Start a game with</h4>
    <table class="table">
    {% for friend in user_friends_list %}
      <tr class="add-user-row">
        <td>
          <img src="{{ friend.picture_url }}"/>
        </td>
        <td>
          {{ friend.name }}
        </td>
        <td>
          <button type="submit" class="btn btn-primary add-user-btn add-user-btn" user_id="{{ friend.user_id }}">Add</button>
        </td>
      </tr>
    {% endfor %}
    </table>
  </div>
  <div class="invite-friends-container most-padding-top">
    <h4>Invite Friends</h4>

    <table class="table">
    {% for friend in fb_friends_list %}
      <tr>
        <td>
          <img src="{{ friend.picture_url }}"/>
        </td>
        <td>
        {{ friend.name }}
        </td>
        <td>
          <button type="submit" class="btn btn-primary">Invite</button>
        </td>
      </tr>
    {% endfor %}
    </table>
  </div>
{%  endblock %}

{% block navbar_bottom %}
  <div class="row-fluid create-game-container">
      <form id="create-form" class="" action="{% url 'create_game' %}" method="post">
        {% csrf_token %}
        {% if gf.users.errors %}
          <div class="alert alert-error">You must add at least two people to your game</div>
        {% endif %}
        <div id="user_friends_checkboxes" class="hidden">
          {{ gf.users }}
        </div>
        <button type="submit" class="btn btn-primary create-game-btn">Start Game</button>
      </form>
  </div>
{% endblock %}

{% block footer_js %}
  <script src="{{ STATIC_URL }}js/contacts.js"></script>
{% endblock %}

templates/draw.html
{% extends "base.html" %}

{% block header_css %}
  <link href="{{ STATIC_URL }}css/contacts.css" rel="stylesheet" type="text/css">
{% endblock %}

{% block css %}
<style type="text/css">
#middle {
 overflow-x:hidden;
 overflow-y:hidden;
}
</style>
{% endblock %}

{% block header_js %}
<script type="text/javascript" src="{{ STATIC_URL }}js/html5-canvas-drawing-app-simple.js"></script>
{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
<p>{{ game.current_turn.game_topic.topic.text }}</p>
<!--[if IE]><script type="text/javascript" src="{{ STATIC_URL }}js/excanvas.js"></script><![endif]-->
<div class="btn-toolbar">
  <div class="btn-group">
    <a class="btn" href="#"><div id="choosePurpleSimpleTools" class="circle" style="background-color:#cb3594"></div></a>
    <a class="btn" href="#"><div id="chooseGreenSimpleTools" class="circle" style="background-color:#659b41"></div></a>
    <a class="btn" href="#"><div id="chooseYellowSimpleTools" class="circle" style="background-color:#ffcf33"></div></a>
    <a class="btn" href="#"><div id="chooseBrownSimpleTools" class="circle" style="background-color:#986928"></div></a>
  </div>
</div>

<div id="canvasSimpleToolsDivOuter">
  <div class="canvasSimpleToolsDiv" name="0">
  </div>
</div>

<div class="btn-toolbar">
  <div class="pencil-btn-group btn-group dropup">
    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#"><i class="icon-pencil"></i><span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li id="chooseSmallSimpleTools" >
        <div class="small-circle"></div>
      </li>
      <li id="chooseNormalSimpleTools">
        <div class="normal-circle"></div>
      </li>
      <li id="chooseLargeSimpleTools" >
        <div class="large-circle"></div>
      </li>
      <li id="chooseHugeSimpleTools" >
        <div class="huge-circle"></div>
      </li>
    </ul>
  </div>
  <div class="btn-group">
    <a class="btn" href="#" id="chooseEraserSimpleTools">E</a>
    <a class="btn" href="#" id="clearCanvasSimpleTools"><i class="icon-trash"></i></a>
  </div>
  <form id="draw-form" class="margin-left" action="{% url 'game' game.id %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="clickX" value="">
      <input type="hidden" name="clickY" value="">
      <input type="hidden" name="clickColor" value="">
      <input type="hidden" name="clickDrag" value="">
      <input type="hidden" name="clickSize" value="">
      <button id="submit-btn" class="btn btn-primary btn-small">Submit</button>
  </form>
</div>
{% endblock %}


{% block footer_js %}
<script type="text/javascript">
  $(document).ready(function(){
    drawingApp.prepareSimpleToolsCanvas();
  });
</script>
{% endblock %}


{% block footer %}
{% endblock %}

templates/games.html
{% extends "base.html" %}

{% block header_css %}
  <link href="{{ STATIC_URL }}css/contacts.css" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
  <div class="more-margin-top more-margin-bottom">
    <a class="btn btn-block btn-info" href="{% url 'create_game' %}">Start a new game</a>
  </div>

  <table class="table table-bordered table-hover games-table">
    <thead>
      <tr>
        <th>Rd</th>
        </th><th colspan="2">Current Games</th>
      </tr>
    </thead>
    <tbody>
      {% for game in games %}
      <tr class="games-table-row" url="{% url 'game' game.id %}">
        <td class="round-col">
          {{ game.current_turn.num }}
        </td>
        <td class="players-col">
            <div class="game-photos">
              {% for user in game.users.all %}
                  <img class="user-image" width="20" title="{{ user.first_name }} {{ user.last_name }}" src="{{ user.facebooksession_set.all.0.picture_url }}" />
              {% endfor %}
            </div>
        </td>
        <td class="game-status-col">
          {% if game.current_turn.status == 0 %}
            {% if user == game.current_turn.judge %}
              Choose a topic
            {% else %}
              Waiting for next topic
            {% endif %}
          {% elif game.current_turn.status == 1 %}
            {% if user == game.current_turn.judge %}
              Choose a winner!
            {% else %}
              Draw "{{ game.current_turn.game_topic.topic.text }}"
            {% endif %}
          {% elif game.current_turn.status == 2 %}
            {% if user == game.current_turn.judge %}
              Turn ended
            {% else %}
              Turn ended
            {% endif %}
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  <table class="table table-bordered table-hover games-table">
    <thead>
      <tr>
        <th>Rd</th>
        <th colspan="2">Completed Games</th>
      </tr>
    </thead>
    <tbody>
      {% for game in completed_games %}
      <tr class="games-table-row" url="{% url 'game' game.id %}">
        <td class="round-col">
          {{ game.current_turn.num }}
        </td>
        <td class="players-col">
          <a href="{% url 'game' game.id %}">
            <div class="game-photos">
              {% for user in game.users.all %}
                  <img class="user-image" width="20" title="{{ user.first_name }} {{ user.last_name }}" src="{{ user.facebooksession_set.all.0.picture_url }}" />
              {% endfor %}
            </div>
          </a>
        </td>
        <td>
          {{ game.winner.user.first_name }} {{ game.winner.user.last_name }}  won!
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

{% block footer_js %}
  <script type="text/javascript">
    $(document).ready(function(){
      $('.user-image').tooltip({

      })

    $('.games-table tbody tr.games-table-row').click(function(){
        var url = $(this).attr('url');
        if(url) {
          window.location = url;
        }
      });
    });
  </script>
{% endblock %}